import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";

export const metadata: Metadata = {
  title: "Terms of Service | The Invisible Patient",
  description: "Terms of Service for The Invisible Patient.",
};

const sections = [
  {
    title: "Eligibility",
    paragraphs: [
      "You must be at least 13 years old to use Invisible Patient.",
      "By creating an account, you represent that the information you provide is accurate.",
    ],
  },
  {
    title: "Accounts",
    paragraphs: [
      "Accounts are authenticated using Google Sign In.",
      "You are responsible for maintaining access to your Google account.",
      "You are responsible for all activity that occurs under your account.",
    ],
  },
  {
    title: "Acceptable Use",
    paragraphs: ["You agree not to:"],
    items: [
      "Use the service for unlawful purposes",
      "Attempt to gain unauthorized access",
      "Interfere with operation of the service",
      "Upload malicious software",
      "Abuse, harass, or threaten others",
      "Attempt to reverse engineer the platform where prohibited by law",
    ],
  },
  {
    title: "AI Features",
    paragraphs: [
      "Invisible Patient includes AI generated responses.",
      "AI responses may be incomplete, may contain mistakes, should be independently verified when important, and should not replace professional medical advice.",
      "You remain responsible for decisions made based on AI generated information.",
    ],
  },
  {
    title: "Medical Disclaimer",
    paragraphs: [
      "Invisible Patient is not a healthcare provider.",
      "The application does not diagnose conditions, prescribe treatment, or replace licensed medical professionals.",
      "Never delay seeking medical care because of information generated by the application.",
    ],
  },
  {
    title: "User Content",
    paragraphs: [
      "You retain ownership of information you submit.",
      "By using the service, you grant Invisible Patient permission to store and process your information solely for the purpose of operating the application.",
    ],
  },
  {
    title: "Intellectual Property",
    paragraphs: [
      "The application, software, branding, and content created by Invisible Patient remain the property of Invisible Patient unless otherwise stated.",
      "You may not copy or redistribute substantial portions of the application without permission.",
    ],
  },
  {
    title: "Availability",
    paragraphs: [
      "We strive to keep the service available but cannot guarantee uninterrupted operation.",
      "The application may occasionally be unavailable due to maintenance, updates, or circumstances beyond our control.",
    ],
  },
  {
    title: "Limitation of Liability",
    paragraphs: [
      "To the fullest extent permitted by law, Invisible Patient shall not be liable for indirect, incidental, consequential, or special damages arising from your use of the service.",
      "Use of the application is at your own risk.",
    ],
  },
  {
    title: "Termination",
    paragraphs: [
      "We may suspend or terminate accounts that violate these Terms or misuse the platform.",
      "You may stop using the application at any time.",
    ],
  },
  {
    title: "Changes",
    paragraphs: [
      "We may modify these Terms periodically.",
      "Continued use of the application after changes become effective constitutes acceptance of the updated Terms.",
    ],
  },
  {
    title: "Governing Law",
    paragraphs: [
      "These Terms shall be governed by the laws of the State of Wisconsin, United States, without regard to conflict of law principles.",
    ],
  },
  {
    title: "Contact",
    paragraphs: [
      "Questions regarding these Terms may be sent to our support team.",
    ],
    contact: true,
  },
];

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      introduction={[
        "Welcome to Invisible Patient.",
        "These Terms govern your use of the Invisible Patient website and services.",
        "By accessing or using the application, you agree to these Terms.",
      ]}
      sections={sections}
    />
  );
}
